"use client";

import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    about: "About Us",
    services: "Services",
    contact: "Contact",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",
    bookAppointment: "Book Appointment",
    viewEcard: "View e-Card",
    generateEcard: "Generate e-Card",
    myAppointments: "My Appointments",
    patientDashboard: "Patient Dashboard",
    doctorDashboard: "Doctor Dashboard",
    pharmacistPanel: "Pharmacist Panel",
    consultation: "Consultation",
    prescriptions: "Prescriptions",
    welcome: "Welcome",
    hospitalName: "All India Institute of Ayurveda",
    govtName: "Government of India",
    tagline: "Quality Healthcare for All",
    emergencyServices: "24/7 Emergency Services",
    helplineText: "Helpline: 1800-XXX-XXXX",
    ecard: "e-Card",
    appointments: "Appointments",
    skipContent: "Skip to main content",
    skipLink: "[Skip Content]",
    screenReader: "[Screen Reader]",
    emblemAlt: "Government of India Emblem",
    email: "Email",
    password: "Password",
    mobile: "Mobile Number",
    otp: "OTP",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember me",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    name: "Full Name",
    dob: "Date of Birth",
    gender: "Gender",
    address: "Address",
    aadhaar: "Aadhaar Number",
    submit: "Submit",
    cancel: "Cancel",
    next: "Next",
    previous: "Previous",
    confirm: "Confirm",
    selectDepartment: "Select Department",
    selectDoctor: "Select Doctor",
    selectDate: "Select Date",
    selectTime: "Select Time Slot",
    appointmentDetails: "Appointment Details",
    patientInfo: "Patient Information",
    consultationNotes: "Consultation Notes",
    prescribeMedication: "Prescribe Medication",
    dispenseMedication: "Dispense Medication",
    printReceipt: "Print Receipt",
    activeAppointments: "Active Appointments",
    activePrescriptions: "Active Prescriptions",
    startConsultation: "Start Consultation",
    ecardNumber: "e-Card Number",
    referenceId: "Reference ID",
    status: "Status",
    date: "Date",
    time: "Time",
    doctor: "Doctor",
    department: "Department",
    patient: "Patient",
    medication: "Medication",
    dosage: "Dosage",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    searchPatient: "Search Patient",
    noAppointments: "No appointments found",
    noPrescriptions: "No prescriptions found",
    appointmentConfirmed: "Appointment Confirmed",
    footerText: "Government of India - AIIA HMS",
    copyright: "All Rights Reserved",
    helpline: "Helpline",
    emergency: "Emergency",
    // Home Page
    latestNews: "Latest News",
    newsTicker: "Token & Queue Management System Live | ABDM Integration Active | Quality Ayurveda Care for All",
    medicalDirector: "Medical Director",
    chiefMedicalOfficer: "Chief Medical Officer",
    hospitalAdministrator: "Hospital Administrator",
    notifications: "Notifications",
    tenders: "Tenders",
    view: "View",
    viewAll: "View All",
    welcomeTitle: "Welcome to All India Institute of Ayurveda",
    welcomeText: "All India Institute of Ayurveda (AIIA) is an apex institute for Ayurveda in India. We provide quality healthcare services with a focus on traditional wisdom and modern science. Our Token & Queue Management system ensures a seamless experience for all patients.",
    knowMore: "Know More",
    ourServices: "Our Services",
    quickAccess: "Quick Access",
    importantLinks: "Important Links",
    patientRights: "Patient Rights",
    healthResources: "Health Resources",
    insurancePartners: "Insurance Partners",
    feedbackPortal: "Feedback Portal",
    onlineAppointment: "Online Appointment",
    ecardRegistration: "e-Card Registration",
    doctorConsultation: "Doctor Consultation",
    emergency247: "24/7 Emergency",
    patientLogin: "Patient Login",
    doctorLogin: "Doctor Login",
    pharmacistLogin: "Pharmacist Login",
    adminLogin: "Admin Login",
    new: "NEW",
    
    // Footer
    contactUs: "Contact Us",
    addressLine1: "Mathura Road, Gautampuri",
    addressLine2: "Sarita Vihar, New Delhi - 110076",
    quickLinks: "Quick Links",
    rti: "RTI",
    sitemap: "Sitemap",
    patientPortal: "Patient Portal",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    disclaimer: "Disclaimer",
    top: "Top",
    
    // Login & Signup
    loginPortal: "Login Portal",
    selectUserType: "Select User Type",
    emailLogin: "Email Login",
    otpLogin: "OTP Login",
    emailOrUserId: "Email / User ID",
    enterEmail: "Enter your email",
    enterPassword: "Enter your password",
    loggingIn: "Logging in...",
    sendOtp: "Send OTP",
    resend: "Resend",
    enterOtp: "Enter OTP",
    enterOtpHolder: "Enter 6-digit OTP",
    enter6DigitOtp: "Enter 6-digit OTP",
    admin: "Admin",
    pharmacist: "Pharmacist",
    demoOtp: "Demo: Use any 6-digit OTP",
    or: "OR",
    and: "and",
    access: "Access",
    registerHere: "Register Here",
    forAssistance: "For any assistance, contact",
    createAccount: "Create your account to access healthcare services",
    enterFullName: "Enter your full name",
    select: "Select",
    male: "Male",
    female: "Female",
    other: "Other",
    enterEmailPlaceholder: "your.email@example.com",
    enterMobilePlaceholder: "10-digit mobile number",
    upcoming: "Upcoming",
    completed: "Completed",
    cancelled: "Cancelled",
    active: "Active",
    accountStatus: "Account Status",
    whatsappUpdates: "Get Updates on WhatsApp",
    dashboardSubtitle: "Manage your appointments and health records from your dashboard.",
    complaint: "Complaint",
    diagnosis: "Diagnosis",
    remarks: "Remarks",
    patientsWaiting: "Patients Waiting",
    upcomingToday: "Upcoming Today",
    completedToday: "Completed Today",
    pendingDiagnosis: "Pending Diagnosis",
    quickActions: "Quick Actions",
    mySchedule: "My Schedule",
    viewAllPatients: "View All Patients",
    createPassword: "Create a password",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    iAgreeTo: "I agree to the",
    termsOfService: "Terms of Service",
    creatingAccount: "Creating account...",
    registrationSuccessful: "Registration Successful!",
    redirecting: "Your account has been created. Redirecting to login...",
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    services: "सेवाएं",
    contact: "संपर्क",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    dashboard: "डैशबोर्ड",
    bookAppointment: "अपॉइंटमेंट बुक करें",
    viewEcard: "ई-कार्ड देखें",
    generateEcard: "ई-कार्ड बनाएं",
    myAppointments: "मेरे अपॉइंटमेंट",
    patientDashboard: "मरीज़ डैशबोर्ड",
    doctorDashboard: "डॉक्टर डैशबोर्ड",
    pharmacistPanel: "फार्मासिस्ट पैनल",
    consultation: "परामर्श",
    prescriptions: "प्रिस्क्रिप्शन",
    welcome: "स्वागत है",
    hospitalName: "अखिल भारतीय आयुर्वेद संस्थान",
    govtName: "भारत सरकार",
    tagline: "सभी के लिए गुणवत्तापूर्ण स्वास्थ्य सेवा",
    emergencyServices: "24/7 आपातकालीन सेवाएं",
    helplineText: "हेल्पलाइन: 1800-XXX-XXXX",
    ecard: "ई-कार्ड",
    appointments: "अपॉइंटमेंट",
    skipContent: "मुख्य सामग्री पर जाएं",
    skipLink: "[विषय सामग्री छोड़ें]",
    screenReader: "[स्क्रीन रीडर]",
    emblemAlt: "भारत सरकार का प्रतीक",
    email: "ईमेल",
    password: "पासवर्ड",
    mobile: "मोबाइल नंबर",
    otp: "ओटीपी",
    forgotPassword: "पासवर्ड भूल गए?",
    rememberMe: "मुझे याद रखें",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से खाता है?",
    name: "पूरा नाम",
    dob: "जन्म तिथि",
    gender: "लिंग",
    address: "पता",
    aadhaar: "आधार नंबर",
    submit: "जमा करें",
    cancel: "रद्द करें",
    next: "अगला",
    previous: "पिछला",
    confirm: "पुष्टि करें",
    selectDepartment: "विभाग चुनें",
    selectDoctor: "डॉक्टर चुनें",
    selectDate: "तारीख चुनें",
    selectTime: "समय स्लॉट चुनें",
    appointmentDetails: "अपॉइंटमेंट विवरण",
    patientInfo: "मरीज़ की जानकारी",
    consultationNotes: "परामर्श नोट्स",
    prescribeMedication: "दवा लिखें",
    dispenseMedication: "दवा वितरण",
    printReceipt: "रसीद प्रिंट करें",
    activeAppointments: "सक्रिय अपॉइंटमेंट",
    activePrescriptions: "सक्रिय प्रिस्क्रिप्शन",
    startConsultation: "परामर्श शुरू करें",
    ecardNumber: "ई-कार्ड नंबर",
    referenceId: "संदर्भ आईडी",
    status: "स्थिति",
    date: "तारीख",
    time: "समय",
    doctor: "डॉक्टर",
    department: "विभाग",
    patient: "मरीज़",
    medication: "दवा",
    dosage: "खुराक",
    frequency: "आवृत्ति",
    duration: "अवधि",
    instructions: "निर्देश",
    searchPatient: "मरीज़ खोजें",
    noAppointments: "कोई अपॉइंटमेंट नहीं मिला",
    noPrescriptions: "कोई प्रिस्क्रिप्शन नहीं मिला",
    appointmentConfirmed: "अपॉइंटमेंट की पुष्टि हुई",
    footerText: "भारत सरकार - AIIA HMS",
    copyright: "सर्वाधिकार सुरक्षित",
    helpline: "हेल्पलाइन",
    emergency: "आपातकालीन",
    // Home Page
    latestNews: "ताज़ा खबर",
    newsTicker: "टोकन और कतार प्रबंधन प्रणाली लाइव | एबीडीएम एकीकरण सक्रिय | सभी के लिए गुणवत्तापूर्ण आयुर्वेद देखभाल",
    medicalDirector: "चिकित्सा निदेशक",
    chiefMedicalOfficer: "मुख्य चिकित्सा अधिकारी",
    hospitalAdministrator: "अस्पताल प्रशासक",
    notifications: "सूचनाएं",
    tenders: "निविदाएं",
    view: "देखें",
    viewAll: "सभी देखें",
    welcomeTitle: "अखिल भारतीय आयुर्वेद संस्थान में आपका स्वागत है",
    welcomeText: "अखिल भारतीय आयुर्वेद संस्थान (AIIA) भारत में आयुर्वेद के लिए एक शीर्ष संस्थान है। हम पारंपरिक ज्ञान और आधुनिक विज्ञान पर ध्यान केंद्रित करते हुए गुणवत्तापूर्ण स्वास्थ्य सेवाएं प्रदान करते हैं। हमारा टोकन और कतार प्रबंधन सिस्टम सभी मरीजों के लिए एक सहज अनुभव सुनिश्चित करता है।",
    knowMore: "और जानें",
    ourServices: "हमारी सेवाएं",
    quickAccess: "त्वरित पहुंच",
    importantLinks: "महत्वपूर्ण लिंक",
    patientRights: "मरीज़ के अधिकार",
    healthResources: "स्वास्थ्य संसाधन",
    insurancePartners: "बीमा भागीदार",
    feedbackPortal: "फीडबैक पोर्टल",
    onlineAppointment: "ऑनलाइन अपॉइंटमेंट",
    ecardRegistration: "ई-कार्ड पंजीकरण",
    doctorConsultation: "डॉक्टर परामर्श",
    emergency247: "24/7 आपातकालीन",
    patientLogin: "मरीज़ लॉगिन",
    doctorLogin: "डॉक्टर लॉगिन",
    pharmacistLogin: "फार्मासिस्ट लॉगिन",
    adminLogin: "एडमिन लॉगिन",
    new: "नया",

    // Footer
    contactUs: "संपर्क करें",
    addressLine1: "मथुरा रोड, गौतमपुरी",
    addressLine2: "सरिता विहार, नई दिल्ली - 110076",
    quickLinks: "त्वरित लिंक",
    rti: "आरटीआई",
    sitemap: "साइटमैप",
    patientPortal: "मरीज़ पोर्टल",
    privacyPolicy: "गोपनीयता नीति",
    termsOfUse: "उपयोग की शर्तें",
    disclaimer: "अस्वीकरण",
    top: "ऊपर",

    // Login & Signup
    loginPortal: "लॉगिन पोर्टल",
    selectUserType: "उपयोगकर्ता प्रकार चुनें",
    emailLogin: "ईमेल लॉगिन",
    otpLogin: "ओटीपी लॉगिन",
    emailOrUserId: "ईमेल / यूजर आईडी",
    enterEmail: "अपना ईमेल दर्ज करें",
    enterPassword: "अपना पासवर्ड दर्ज करें",
    loggingIn: "लॉगिन कर रहा है...",
    sendOtp: "ओटीपी भेजें",
    resend: "पुनः भेजें",
    enterOtp: "ओटीपी दर्ज करें",
    enterOtpHolder: "6-अंकीय ओटीपी दर्ज करें",
    enter6DigitOtp: "6-अंकीय ओटीपी दर्ज करें",
    admin: "एडमिन",
    pharmacist: "फार्मासिस्ट",
    demoOtp: "डेमो: कोई भी 6-अंकीय ओटीपी उपयोग करें",
    or: "या",
    and: "और",
    access: "एक्सेस",
    registerHere: "यहाँ रजिस्टर करें",
    forAssistance: "किसी भी सहायता के लिए संपर्क करें",
    createAccount: "स्वास्थ्य सेवाओं का उपयोग करने के लिए अपना खाता बनाएं",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    select: "चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    enterEmailPlaceholder: "your.email@example.com",
    enterMobilePlaceholder: "10-अंकीय मोबाइल नंबर",
    upcoming: "आगामी",
    completed: "पूर्ण",
    cancelled: "रद्द",
    active: "सक्रिय",
    accountStatus: "खाता स्थिति",
    whatsappUpdates: "व्हाट्सएप पर अपडेट प्राप्त करें",
    dashboardSubtitle: "अपने डैशबोर्ड से अपने अपॉइंटमेंट और स्वास्थ्य रिकॉर्ड प्रबंधित करें।",
    complaint: "शिकायत",
    diagnosis: "निदान",
    remarks: "टिप्पणियों",
    patientsWaiting: "प्रतीक्षारत मरीज़",
    upcomingToday: "आज आगामी",
    completedToday: "आज पूर्ण",
    pendingDiagnosis: "लंबित निदान",
    quickActions: "त्वरित कार्रवाई",
    mySchedule: "मेरी अनुसूची",
    viewAllPatients: "सभी मरीज़ देखें",
    createPassword: "पासवर्ड बनाएं",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    confirmPasswordPlaceholder: "अपने पासवर्ड की पुष्टि करें",
    iAgreeTo: "मैं सहमत हूं",
    termsOfService: "सेवा की शर्तें",
    creatingAccount: "खाता बना रहा है...",
    registrationSuccessful: "पंजीकरण सफल!",
    redirecting: "आपका खाता बन गया है। लॉगिन पर रीडायरेक्ट कर रहा है...",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
